#!/usr/bin/env python3
"""
Grant Scanner v3 — Radar de Oportunidades para Jornalismo Investigativo

Author: Reinaldo Chaves (https://github.com/reichaves/grant-scanner)
License: MIT
"""

import os
import sys
import re
import json
import logging
import smtplib
import hashlib
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from datetime import datetime, timezone, timedelta
from pathlib import Path
from typing import Optional

try:
    import requests
    HAS_REQUESTS = True
except ImportError:
    HAS_REQUESTS = False

from google import genai
from google.genai import types

# ---------------------------------------------------------------------------
# Configuration
# ---------------------------------------------------------------------------

LOG_FORMAT = "%(asctime)s [%(levelname)s] %(message)s"
logging.basicConfig(level=logging.INFO, format=LOG_FORMAT)
logger = logging.getLogger(__name__)

BRT = timezone(timedelta(hours=-3))

SENDER_EMAIL = "reichaves@gmail.com"

RECIPIENTS = [
    "reinaldo@abraji.org.br",
    "anacarolinamoreno@abraji.org.br",
    "sergioludtke@abraji.org.br",
    "leticiakleim@abraji.org.br",
]


"""
RECIPIENTS = [
    "reinaldo@abraji.org.br"
]
"""
# ---------------------------------------------------------------------------
# Model Configuration
# ---------------------------------------------------------------------------
GEMINI_MODEL = "gemini-3-pro-preview"
PREVIOUS_REPORT_PATH = "previous_grant_report.json"

# ---------------------------------------------------------------------------
# Standardized Header/Footer — NOT generated by the LLM
# ---------------------------------------------------------------------------
HEADER_TEMPLATE = """RELATÓRIO DE OPORTUNIDADES DE FINANCIAMENTO: JORNALISMO E MÍDIA
Data do Relatório: {today}
Preparado para: Abraji (Associação Brasileira de Jornalismo Investigativo)
Período de cobertura: Oportunidades com prazo aberto ou previsto para {year}
Total de oportunidades identificadas: {total_count}
├─ ✅ Elegibilidade confirmada: {confirmed_count}
├─ ⚠️ Elegibilidade a verificar: {unverified_count}
└─ 🔴 Prazo urgente (< 30 dias): {urgent_count}

LEGENDA DE URGÊNCIA:
🔴 URGENTE — Prazo em menos de 30 dias
🟡 ATENÇÃO — Prazo entre 30 e 90 dias
🟢 PLANEJAMENTO — Prazo acima de 90 dias ou fluxo contínuo

LEGENDA DE ELEGIBILIDADE:
✅ CONFIRMADA — Página oficial menciona Brasil/LatAm/Global explicitamente
⚠️ NÃO VERIFICADA — Elegibilidade para o Brasil não pôde ser confirmada na fonte
🔗 PARCIAL — Brasil elegível como parceiro, não como aplicante principal
"""

FOOTER_TEMPLATE = """
---
Gerado automaticamente via GitHub Actions · Powered by Google {model}
Abraji — Associação Brasileira de Jornalismo Investigativo
⚠️ Este relatório usa IA e busca web automatizada. Sempre verifique os links e prazos nos sites oficiais.
Script criado por Reinaldo Chaves (https://github.com/reichaves/grant-scanner)
"""

# ---------------------------------------------------------------------------
# Prompts — v3 with Eligibility Verification Protocol
# ---------------------------------------------------------------------------

SYSTEM_PROMPT = """Você é um Especialista Sênior em Fundraising e Desenvolvimento Institucional para organizações de mídia e jornalismo investigativo na América Latina.

Sua tarefa é realizar uma varredura profunda na web para identificar oportunidades de financiamento abertas ou previstas.

PARÂMETROS DE BUSCA:
1. Priorize oportunidades de:
   a) Fundações globais: Open Society, Luminate, Ford Foundation, MacArthur, Knight Foundation, Bloomberg, Hewlett Foundation, Oak Foundation
   b) Agências de cooperação: USAID, EuropeAid, Norad, GIZ, SIDA, AFD, DFAT, IDRC (Canadá)
   c) Organizações de jornalismo: Pulitzer Center, GIJN, Google News Initiative, Internews, Free Press Unlimited, DW Akademie, RSF, NED, IJ4EU, Journalism Science Alliance, Solutions Journalism Network, ICFJ
   d) Fundos temáticos: Global Forest Watch, Climate & Land Use Alliance, ClimateWorks, Skoll Foundation, Omidyar Network
   e) Organizações brasileiras/regionais: Fundo Brasil de Direitos Humanos, Fundação Tide Setubal, Instituto Serrapilheira, Fundação Lemann, Embaixada dos EUA no Brasil, Instituto Igarapé, Fundação Itaú, Fundação Roberto Marinho

2. Busque por termos-chave em inglês, espanhol e português:
   - "Call for proposals journalism 2025 2026"
   - "Investigative reporting grants Latin America"
   - "Media development funding open call"
   - "Fellowships for journalists 2025 2026"
   - "Edital jornalismo investigativo 2025 2026"
   - "Grant for data journalism AI"
   - "Environmental journalism funding"
   - "Press freedom grants"
   - "AI journalism grants newsrooms"
   - "Grants for newsrooms Global South"
   - "Transparency and accountability grants"
   - "Anti-corruption journalism funding"
   - "Digital rights and democracy grants"
   - "Human rights defenders funding Brazil"
   - "Fact-checking and disinformation grants"
   - "Open data civic tech grants"
   - "Collaborative cross-border journalism funding"
   - "Safety of journalists grants"
   - "Climate change environmental media grants"
   - "Financiamento defesa liberdade de imprensa 2026"
   - "Apoio jornalismo local independente edital"
   - "Gender equity in media grants"
   - "Public interest technology funding"
   - "Edital transparência pública dados abertos"
   - "Subvenciones periodismo investigativo América Latina"
   - "Grants journalism"
   - "Edital jornalismo"

3. IGNORE oportunidades exclusivas para cidadãos dos EUA ou UE. Foque naquelas abertas a brasileiros, latino-americanos ou candidatos globais.

══════════════════════════════════════════════════════════════════
PROTOCOLO DE VERIFICAÇÃO DE ELEGIBILIDADE (OBRIGATÓRIO)
══════════════════════════════════════════════════════════════════

Este é o passo MAIS IMPORTANTE de toda a tarefa. Grants com elegibilidade
incorreta causam desperdício de tempo e recursos da equipe.

Para CADA oportunidade encontrada, você DEVE executar estes passos:

PASSO 1 — LOCALIZAR A PÁGINA DE ELEGIBILIDADE:
   Busque na página oficial a seção "Eligibility", "Who can apply",
   "Elegibilidade", "Quem pode participar", "Países elegíveis" ou similar.

PASSO 2 — IDENTIFICAR RESTRIÇÕES GEOGRÁFICAS:
   Procure por termos como:
   - Restrições por região: "Asia-Pacific only", "EU member states",
     "Africa", "MENA region", "Pacific Island countries"
   - Lista fechada de países: "eligible countries: Malaysia, Thailand..."
   - Restrições por sede: "organizations headquartered in..."
   - Exclusões: "not open to organizations in..."

PASSO 3 — VERIFICAR ELEGIBILIDADE PARA O BRASIL:
   O Brasil é elegível SOMENTE se UMA destas condições for verdadeira:
   a) "Brazil" ou "Brasil" está EXPLICITAMENTE listado como país elegível
   b) "Latin America" ou "América Latina" está listada como região elegível
   c) "Global South" ou "developing countries" está listado E não há exclusões
   d) A chamada é explicitamente "global" / "open to all countries"
   e) É um edital brasileiro (organização brasileira, em português)

PASSO 4 — CLASSIFICAR A CONFIANÇA:
   - "confirmed": Verificou a página oficial E Brasil/LatAm está explicitamente elegível
   - "likely": A chamada parece global mas não lista países explicitamente
   - "partial": Brasil elegível apenas como PARCEIRO (não líder), ex: IJ4EU
   - "unverified": Não conseguiu acessar a página de elegibilidade ou não encontrou informação clara
   - "ineligible": Confirmou que Brasil NÃO é elegível (NÃO INCLUA no resultado)

REGRA DE OURO: Na dúvida, marque como "unverified". NUNCA marque "confirmed"
sem ter verificado a página oficial. É melhor ter um falso "unverified" do
que um falso "confirmed".

EXEMPLO DE FALSO POSITIVO A EVITAR:
O grant "UNDP Agents of Change" parece perfeito tematicamente (mídia,
desinformação, transparência) mas é EXCLUSIVO para Ásia-Pacífico
(Malásia, Tailândia, Mongólia, Indonésia). Grants como esse devem
receber "ineligible" e ser EXCLUÍDOS.

══════════════════════════════════════════════════════════════════

FILTRAGEM RIGOROSA:
- Inclua APENAS oportunidades com prazo de inscrição FUTURO (após {today}) OU fluxo contínuo (rolling).
- Se um edital encerrou recentemente mas tem ciclo anual previsível, inclua com nota "Próximo ciclo previsto para [estimativa]".
- Se não conseguir confirmar que o prazo está aberto, indique "⚠️ Verificar no site" em vez de inventar uma data.
- NÃO inclua prêmios (awards) com valor inferior a USD 2.000 — foque em grants substantivos.
- EXCLUA oportunidades onde confirmou que o Brasil NÃO é elegível (eligibility_confidence = "ineligible").

FORMATO DE SAÍDA (OBRIGATÓRIO — siga EXATAMENTE este formato JSON):

Retorne UM JSON válido com a seguinte estrutura:
```json
{{
  "opportunities": [
    {{
      "name": "Nome completo do grant/fundo",
      "funder": "Nome da organização financiadora",
      "summary": "O que financiam — máx. 2 frases claras",
      "amount_usd_min": 5000,
      "amount_usd_max": 20000,
      "amount_display": "USD 5.000 – USD 20.000",
      "deadline": "2026-03-15",
      "deadline_display": "15 de março de 2026",
      "deadline_type": "fixed",
      "eligibility": "Descrição clara da elegibilidade para brasileiros/latino-americanos",
      "eligibility_confidence": "confirmed",
      "eligibility_source": "https://example.org/call-for-proposals#eligibility",
      "eligible_regions": ["Latin America", "Global"],
      "brazil_eligible": true,
      "url": "https://example.org/apply",
      "themes": ["investigative journalism", "environmental", "data"],
      "type": "grant"
    }}
  ],
  "strategic_recommendations": [
    {{
      "title": "Título da recomendação",
      "action": "Ação específica e acionável",
      "strategy": "Estratégia detalhada",
      "relevant_opportunities": ["Nome do grant 1", "Nome do grant 2"],
      "deadline_action": "Data limite para começar a preparar"
    }}
  ]
}}
```

REGRAS DO JSON:
- "deadline_type": use "fixed" (data exata), "rolling" (contínuo), ou "estimated" (previsão)
- "deadline": use formato ISO "YYYY-MM-DD". Para rolling use "rolling". Para estimativa use a melhor estimativa.
- "type": use "grant", "fellowship", "fund", ou "emergency"
- "themes": lista de tags temáticas em inglês (para filtragem)
- "amount_usd_min" e "amount_usd_max": valores numéricos em USD. Use 0 se não divulgado.
- "url": DEVE ser a URL direta da página de aplicação, NÃO a home page genérica.
- "eligibility_confidence": OBRIGATÓRIO — "confirmed", "likely", "partial", ou "unverified"
- "eligibility_source": URL onde verificou a elegibilidade (pode ser a mesma do grant)
- "eligible_regions": Lista de regiões/países elegíveis conforme a fonte oficial
- "brazil_eligible": true, false, ou null (se não conseguiu confirmar)

IMPORTANTE:
- Encontre no MÍNIMO 12 oportunidades, idealmente 15-20.
- NÃO invente informações. Se não tiver certeza, indique claramente.
- NÃO inclua oportunidades onde brazil_eligible é false.
- Retorne APENAS o JSON, sem texto adicional antes ou depois.

RECOMENDAÇÕES ESTRATÉGICAS:
As 3 recomendações devem considerar que a Abraji:
- Tem 20+ anos de história e é referência regional em jornalismo investigativo
- Tem o projeto Comprova de combate a desinformação
- Tem um programa de proteção legal, digital e física para jornalistas e de combate ao assédio judicial
- Desenvolve ferramentas de dados (CruzaGrafos com 89M+ registros, Monitor de Assédio Judicial Contra Jornalistas)
- Organiza o maior congresso de jornalismo investigativo do Brasil (1.500+ participantes)
- Tem parcerias internacionais ativas (GIJN, Pulitzer Center, Google News Initiative)
- Trabalha com IA aplicada ao jornalismo e treinamento de redações
- Atua em jornalismo ambiental e monitoramento de dados públicos"""

USER_PROMPT_TEMPLATE = """Data de hoje: {today}

Execute a varredura completa de oportunidades de financiamento conforme as instruções do sistema.

Busque ativamente na web por grants, fellowships e editais para:
1. Jornalismo investigativo e mídia independente
2. Projetos de dados, IA e tecnologia cívica para jornalismo
3. Jornalismo ambiental e climático
4. Liberdade de imprensa e segurança de jornalistas
5. Transparência, anticorrupção e democracia
6. Capacitação e desenvolvimento institucional para organizações de mídia
7. Combate a desinformação

Foco: América Latina, com elegibilidade para organizações e profissionais brasileiros.
Idiomas de busca: EN, ES, PT.

LEMBRETE CRÍTICO: Para cada oportunidade, execute o Protocolo de Verificação de
Elegibilidade COMPLETO antes de incluí-la. Preencha eligibility_confidence,
eligibility_source, eligible_regions e brazil_eligible para CADA item.

Seja exaustivo e retorne o JSON conforme especificado."""

# Second pass prompt — same as v2
SECOND_PASS_PROMPT = """Data de hoje: {today}

Na primeira varredura, já foram encontradas estas oportunidades:
{found_names}

Agora faça uma SEGUNDA varredura buscando oportunidades que NÃO estejam na lista acima.

Foque especificamente em:
1. Editais BRASILEIROS (fundações nacionais, editais governamentais, embaixadas)
2. Oportunidades de TECNOLOGIA e INOVAÇÃO aplicadas ao jornalismo (IA, dados, civic tech)
3. Fundos de EMERGÊNCIA e segurança para jornalistas
4. Fellowships individuais para jornalistas
5. Oportunidades TRANSFRONTEIRIÇAS (Europa-LatAm, Norte-Sul)
6. Fundos climáticos e ambientais que aceitem projetos de mídia

LEMBRETE: Execute o Protocolo de Verificação de Elegibilidade para cada item.
Retorne o JSON no mesmo formato, incluindo APENAS oportunidades NOVAS.
Se encontrar menos de 5 novas, tudo bem — qualidade importa mais que quantidade."""

# ---------------------------------------------------------------------------
# NEW IN v3: Pass 3 — Adversarial Eligibility Audit
# ---------------------------------------------------------------------------
# This prompt instructs the LLM to act as a SKEPTIC AUDITOR whose job is
# to DISPROVE eligibility. This adversarial approach catches cases like
# the UNDP "Agents of Change" where the grant exists but isn't for Brazil.

ELIGIBILITY_AUDIT_PROMPT = """Data de hoje: {today}

Você é um AUDITOR DE ELEGIBILIDADE. Seu trabalho é verificar se organizações
BRASILEIRAS são realmente elegíveis para cada oportunidade listada abaixo.

Sua postura deve ser CÉTICA: assuma que a elegibilidade pode estar ERRADA
e busque EVIDÊNCIAS na web para confirmar ou refutar.

OPORTUNIDADES A AUDITAR:
{opportunities_to_audit}

Para CADA oportunidade acima:
1. Busque a página oficial do edital/grant na web
2. Localize a seção de elegibilidade ("Who can apply", "Eligibility", etc.)
3. Verifique se há RESTRIÇÃO GEOGRÁFICA que exclua o Brasil
4. Procure por listas fechadas de países (ex: "only for Asia-Pacific countries")

Retorne um JSON com o resultado da auditoria:
```json
{{
  "audit_results": [
    {{
      "name": "Nome exato da oportunidade (como recebido)",
      "brazil_eligible": true,
      "eligibility_confidence": "confirmed",
      "audit_notes": "Página oficial em example.org/eligibility confirma: open to Latin America",
      "eligible_regions_found": ["Latin America", "Africa", "Asia"],
      "disqualification_reason": null
    }},
    {{
      "name": "UNDP Agents of Change",
      "brazil_eligible": false,
      "eligibility_confidence": "confirmed",
      "audit_notes": "Página do UNDP especifica: eligible countries are Malaysia, Thailand, Mongolia, Indonesia only",
      "eligible_regions_found": ["Asia-Pacific"],
      "disqualification_reason": "Grant é exclusivo para países da Ásia-Pacífico"
    }}
  ]
}}
```

REGRAS:
- Se NÃO conseguir encontrar a página de elegibilidade, marque eligibility_confidence como "unverified"
- Se encontrar evidência de que o Brasil NÃO é elegível, marque brazil_eligible como false
- Se confirmar elegibilidade, marque brazil_eligible como true e eligibility_confidence como "confirmed"
- Inclua a URL ou descrição da fonte em audit_notes
- Retorne APENAS o JSON"""


def get_env_var(name: str) -> str:
    """Retrieve a required environment variable or exit."""
    value = os.environ.get(name)
    if not value:
        logger.error(f"Environment variable '{name}' is not set.")
        sys.exit(1)
    return value


# ---------------------------------------------------------------------------
# JSON Parsing & Validation
# ---------------------------------------------------------------------------

def extract_json_from_response(text: str) -> Optional[dict]:
    """Extract and parse JSON from LLM response, handling markdown fences."""
    text = text.strip()

    if text.startswith("```"):
        text = re.sub(r"^```(?:json)?\s*\n?", "", text)
        text = re.sub(r"\n?```\s*$", "", text)
        text = text.strip()

    try:
        return json.loads(text)
    except json.JSONDecodeError:
        pass

    match = re.search(r'\{[\s\S]*\}', text)
    if match:
        try:
            return json.loads(match.group())
        except json.JSONDecodeError:
            pass

    logger.warning("Could not parse JSON from response. Falling back to raw text.")
    return None


def validate_opportunity(opp: dict) -> dict:
    """Validate and normalize a single opportunity entry, including eligibility fields."""
    # Required fields
    required_fields = ["name", "funder", "summary", "url"]
    for field in required_fields:
        if field not in opp or not opp[field]:
            opp[field] = "⚠️ Não informado"

    # Normalize deadline
    if "deadline" not in opp:
        opp["deadline"] = "rolling"
        opp["deadline_type"] = "rolling"
        opp["deadline_display"] = "Fluxo contínuo"

    if "deadline_type" not in opp:
        opp["deadline_type"] = "fixed" if opp.get("deadline", "").count("-") == 2 else "rolling"

    if "deadline_display" not in opp:
        opp["deadline_display"] = opp.get("deadline", "Verificar no site")

    # Amount fields
    if "amount_display" not in opp or not opp["amount_display"]:
        opp["amount_display"] = "Não divulgado"

    for field in ["amount_usd_min", "amount_usd_max"]:
        if field not in opp:
            opp[field] = 0

    if "themes" not in opp:
        opp["themes"] = []

    if "type" not in opp:
        opp["type"] = "grant"

    if "eligibility" not in opp:
        opp["eligibility"] = "Verificar no site"

    # ---------------------------------------------------------------------------
    # NEW IN v3: Eligibility verification fields
    # ---------------------------------------------------------------------------
    # eligibility_confidence: How sure are we about the eligibility?
    #   "confirmed" — verified on official page
    #   "likely" — appears global but no explicit country list
    #   "partial" — eligible as partner only (not lead)
    #   "unverified" — could not confirm
    if "eligibility_confidence" not in opp:
        opp["eligibility_confidence"] = "unverified"

    # eligibility_source: URL where eligibility was checked
    if "eligibility_source" not in opp:
        opp["eligibility_source"] = ""

    # eligible_regions: List of regions/countries from official source
    if "eligible_regions" not in opp:
        opp["eligible_regions"] = []

    # brazil_eligible: Explicit boolean — is Brazil eligible?
    # null/None means "not confirmed either way" → treated as unverified
    if "brazil_eligible" not in opp:
        opp["brazil_eligible"] = None

    return opp


def classify_urgency(opp: dict, today: datetime) -> str:
    """Classify opportunity urgency based on deadline proximity."""
    if opp.get("deadline_type") == "rolling":
        return "🟢"

    deadline_str = opp.get("deadline", "")
    if not deadline_str or deadline_str == "rolling" or "verificar" in deadline_str.lower():
        return "🟢"

    try:
        deadline_date = datetime.strptime(deadline_str, "%Y-%m-%d").replace(tzinfo=BRT)
        days_until = (deadline_date - today).days

        if days_until < 0:
            return "⚫"
        elif days_until <= 30:
            return "🔴"
        elif days_until <= 90:
            return "🟡"
        else:
            return "🟢"
    except ValueError:
        return "🟢"


def classify_eligibility_display(opp: dict) -> str:
    """Return display emoji for eligibility confidence level."""
    conf = opp.get("eligibility_confidence", "unverified")
    if conf == "confirmed":
        return "✅"
    elif conf == "likely":
        return "✅"  # likely is good enough for main list
    elif conf == "partial":
        return "🔗"
    else:  # unverified
        return "⚠️"


def deduplicate_opportunities(opps: list[dict]) -> list[dict]:
    """Remove duplicate opportunities based on name similarity."""
    seen = {}
    unique = []

    for opp in opps:
        key = re.sub(r'[^a-z0-9]', '', opp.get("name", "").lower())
        short_key = key[:30]

        if key not in seen and short_key not in seen:
            seen[key] = True
            seen[short_key] = True
            unique.append(opp)
        else:
            logger.info(f"Dedup: removed duplicate '{opp.get('name', 'unknown')}'")

    return unique


def sort_opportunities(opps: list[dict], today: datetime) -> list[dict]:
    """Sort opportunities: urgent first, then by deadline, rolling last."""
    def sort_key(opp):
        deadline_str = opp.get("deadline", "")
        if opp.get("deadline_type") == "rolling" or deadline_str == "rolling":
            return (2, datetime(2099, 12, 31, tzinfo=BRT))
        try:
            d = datetime.strptime(deadline_str, "%Y-%m-%d").replace(tzinfo=BRT)
            return (0 if (d - today).days <= 30 else 1, d)
        except ValueError:
            return (2, datetime(2099, 12, 31, tzinfo=BRT))

    return sorted(opps, key=sort_key)


# ---------------------------------------------------------------------------
# NEW IN v3: Eligibility Filtering
# ---------------------------------------------------------------------------

def filter_by_eligibility(opps: list[dict]) -> tuple[list[dict], list[dict]]:
    """
    Split opportunities into confirmed and unverified based on eligibility.

    Returns:
        Tuple of (confirmed_list, unverified_list)
        - confirmed_list: brazil_eligible is True or confidence is confirmed/likely
        - unverified_list: brazil_eligible is None or confidence is unverified/partial
    """
    confirmed = []
    unverified = []

    for opp in opps:
        # Explicitly ineligible → REMOVE completely (don't even show)
        if opp.get("brazil_eligible") is False:
            logger.info(
                f"Eligibility filter: REMOVED '{opp.get('name')}' "
                f"(brazil_eligible=false, reason: {opp.get('eligibility', 'N/A')})"
            )
            continue

        confidence = opp.get("eligibility_confidence", "unverified")

        if confidence in ("confirmed", "likely") and opp.get("brazil_eligible") is True:
            confirmed.append(opp)
        elif confidence == "partial":
            # Partial eligibility (e.g., partner only) → show in unverified with note
            unverified.append(opp)
        else:
            # unverified, or brazil_eligible is None
            unverified.append(opp)

    logger.info(
        f"Eligibility filter: {len(confirmed)} confirmed, "
        f"{len(unverified)} unverified, "
        f"{len(opps) - len(confirmed) - len(unverified)} removed"
    )

    return confirmed, unverified


def apply_audit_results(opps: list[dict], audit_results: list[dict]) -> list[dict]:
    """
    Merge Pass 3 audit results back into the opportunity list.

    The audit may downgrade eligibility_confidence or set brazil_eligible=false.
    """
    # Build lookup by normalized name
    audit_map = {}
    for ar in audit_results:
        key = re.sub(r'[^a-z0-9]', '', ar.get("name", "").lower())
        audit_map[key] = ar

    updated = []
    for opp in opps:
        key = re.sub(r'[^a-z0-9]', '', opp.get("name", "").lower())

        if key in audit_map:
            ar = audit_map[key]

            # Audit says NOT eligible → override
            if ar.get("brazil_eligible") is False:
                opp["brazil_eligible"] = False
                opp["eligibility_confidence"] = "confirmed"
                opp["eligibility"] += (
                    f" — ❌ AUDITORIA: {ar.get('disqualification_reason', 'Brasil não elegível')}"
                )
                logger.info(
                    f"Audit override: '{opp.get('name')}' marked as INELIGIBLE — "
                    f"{ar.get('disqualification_reason', 'no reason')}"
                )

            # Audit confirms eligibility → upgrade confidence
            elif ar.get("brazil_eligible") is True:
                if ar.get("eligibility_confidence") == "confirmed":
                    opp["eligibility_confidence"] = "confirmed"
                    opp["brazil_eligible"] = True
                    if ar.get("audit_notes"):
                        opp["eligibility_source"] = ar.get("audit_notes", "")

            # Audit found regions info → update
            if ar.get("eligible_regions_found"):
                opp["eligible_regions"] = ar["eligible_regions_found"]

        updated.append(opp)

    return updated


# ---------------------------------------------------------------------------
# Link Validation
# ---------------------------------------------------------------------------

def validate_links(opps: list[dict]) -> list[dict]:
    """Check if URLs are reachable. Mark broken ones."""
    if not HAS_REQUESTS:
        logger.info("Skipping link validation (requests not installed)")
        return opps

    for opp in opps:
        url = opp.get("url", "")
        if not url or url.startswith("⚠️"):
            continue

        if not url.startswith("http"):
            opp["url"] = f"https://{url}"
            url = opp["url"]

        try:
            resp = requests.head(url, timeout=10, allow_redirects=True,
                                 headers={"User-Agent": "Mozilla/5.0 Grant-Scanner/3.0"})
            if resp.status_code >= 400:
                opp["url"] = f"{url} ⚠️ (HTTP {resp.status_code} — verificar manualmente)"
                logger.warning(f"Broken link ({resp.status_code}): {url}")
        except requests.RequestException as e:
            opp["url"] = f"{url} ⚠️ (não acessível — verificar manualmente)"
            logger.warning(f"Link check failed for {url}: {e}")

    return opps


# ---------------------------------------------------------------------------
# Gemini API Call — 3-pass search with eligibility audit
# ---------------------------------------------------------------------------

def run_grant_search(api_key: str) -> dict:
    """
    Three-pass search:
      Pass 1: Broad sweep
      Pass 2: Targeted search for missed opportunities
      Pass 3: Adversarial eligibility audit (NEW in v3)
    """
    client = genai.Client(api_key=api_key)
    today_dt = datetime.now(BRT)
    today = today_dt.strftime("%d/%m/%Y (%A)")

    google_search_tool = types.Tool(
        google_search=types.GoogleSearch()
    )

    config = types.GenerateContentConfig(
        system_instruction=SYSTEM_PROMPT.format(today=today),
        tools=[google_search_tool],
        temperature=0.1,
        max_output_tokens=16000,
        thinking_config=types.ThinkingConfig(
            thinking_level="HIGH"
        ),
    )

    # --- PASS 1: Broad sweep ---
    logger.info(f"PASS 1: Broad sweep — model={GEMINI_MODEL}, date={today}")
    user_prompt = USER_PROMPT_TEMPLATE.format(today=today)

    all_opportunities = []
    all_recommendations = []

    try:
        response = client.models.generate_content(
            model=GEMINI_MODEL,
            contents=user_prompt,
            config=config,
        )

        _log_grounding_metadata(response)
        data = extract_json_from_response(response.text)

        if data and "opportunities" in data:
            all_opportunities.extend(data["opportunities"])
            logger.info(f"Pass 1 found {len(data['opportunities'])} opportunities")
            if "strategic_recommendations" in data:
                all_recommendations = data["strategic_recommendations"]
        else:
            logger.warning("Pass 1: Could not parse structured data. Using raw text.")
            return {"raw_text": response.text, "parse_failed": True}

    except Exception as e:
        logger.error(f"Gemini API error (Pass 1): {e}")
        sys.exit(1)

    # --- PASS 2: Targeted search for missed opportunities ---
    logger.info("PASS 2: Targeted search for missed opportunities")

    found_names = "\n".join(
        f"- {opp.get('name', 'Unknown')}" for opp in all_opportunities
    )

    second_prompt = SECOND_PASS_PROMPT.format(
        today=today,
        found_names=found_names,
    )

    try:
        response2 = client.models.generate_content(
            model=GEMINI_MODEL,
            contents=second_prompt,
            config=config,
        )

        _log_grounding_metadata(response2)
        data2 = extract_json_from_response(response2.text)

        if data2 and "opportunities" in data2:
            all_opportunities.extend(data2["opportunities"])
            logger.info(f"Pass 2 found {len(data2['opportunities'])} additional opportunities")
            if "strategic_recommendations" in data2 and not all_recommendations:
                all_recommendations = data2["strategic_recommendations"]

    except Exception as e:
        logger.warning(f"Pass 2 failed (non-fatal): {e}")

    # --- Post-processing before audit ---
    all_opportunities = [validate_opportunity(opp) for opp in all_opportunities]
    all_opportunities = deduplicate_opportunities(all_opportunities)
    all_opportunities = [
        opp for opp in all_opportunities
        if classify_urgency(opp, today_dt) != "⚫"
    ]

    # =========================================================================
    # PASS 3: Adversarial Eligibility Audit (NEW in v3)
    # =========================================================================
    # This pass acts as a "skeptic auditor" that tries to DISPROVE eligibility.
    # It receives the full list and checks each one against official sources.
    logger.info("PASS 3: Adversarial eligibility audit")

    # Build the list of opportunities to audit
    audit_list = "\n".join(
        f"{i+1}. {opp.get('name', 'Unknown')} — Financiador: {opp.get('funder', 'Unknown')} — "
        f"URL: {opp.get('url', 'N/A')} — "
        f"Elegibilidade declarada: {opp.get('eligibility', 'N/A')} — "
        f"Regiões declaradas: {', '.join(opp.get('eligible_regions', ['N/A']))}"
        for i, opp in enumerate(all_opportunities)
    )

    audit_prompt = ELIGIBILITY_AUDIT_PROMPT.format(
        today=today,
        opportunities_to_audit=audit_list,
    )

    # Audit uses a separate config (no system instruction, just the audit prompt)
    audit_config = types.GenerateContentConfig(
        tools=[google_search_tool],
        temperature=0.0,  # Maximum factuality for audit
        max_output_tokens=12000,
        thinking_config=types.ThinkingConfig(
            thinking_level="HIGH"
        ),
    )

    try:
        response3 = client.models.generate_content(
            model=GEMINI_MODEL,
            contents=audit_prompt,
            config=audit_config,
        )

        _log_grounding_metadata(response3)
        audit_data = extract_json_from_response(response3.text)

        if audit_data and "audit_results" in audit_data:
            audit_results = audit_data["audit_results"]
            logger.info(f"Pass 3 audited {len(audit_results)} opportunities")

            # Apply audit results: may override eligibility
            all_opportunities = apply_audit_results(all_opportunities, audit_results)

            # Count disqualifications
            disqualified = sum(
                1 for ar in audit_results if ar.get("brazil_eligible") is False
            )
            if disqualified > 0:
                logger.info(f"Pass 3 disqualified {disqualified} opportunities")
        else:
            logger.warning("Pass 3: Could not parse audit results. Continuing without audit.")

    except Exception as e:
        logger.warning(f"Pass 3 (audit) failed (non-fatal): {e}")

    # --- Final post-processing ---
    all_opportunities = validate_links(all_opportunities)

    for opp in all_opportunities:
        opp["urgency"] = classify_urgency(opp, today_dt)

    all_opportunities = sort_opportunities(all_opportunities, today_dt)

    # Split into confirmed and unverified
    confirmed, unverified = filter_by_eligibility(all_opportunities)

    logger.info(
        f"Final: {len(confirmed)} confirmed + {len(unverified)} unverified = "
        f"{len(confirmed) + len(unverified)} total"
    )

    return {
        "opportunities_confirmed": confirmed,
        "opportunities_unverified": unverified,
        "opportunities": confirmed + unverified,  # Combined for backward compat
        "strategic_recommendations": all_recommendations,
        "generated_at": today_dt.isoformat(),
        "model": GEMINI_MODEL,
        "stats": {
            "pass1_count": len(all_opportunities),  # Before filtering
            "confirmed_count": len(confirmed),
            "unverified_count": len(unverified),
            "removed_count": len(all_opportunities) - len(confirmed) - len(unverified),
        },
    }


def _log_grounding_metadata(response) -> None:
    """Log search queries and grounding info from the API response."""
    try:
        if response.candidates and response.candidates[0].grounding_metadata:
            metadata = response.candidates[0].grounding_metadata
            if metadata.web_search_queries:
                logger.info(f"Search queries: {metadata.web_search_queries}")
            if metadata.grounding_chunks:
                logger.info(f"Grounding sources: {len(metadata.grounding_chunks)} chunks")
    except Exception:
        pass


# ---------------------------------------------------------------------------
# Report Formatting
# ---------------------------------------------------------------------------

def format_report_markdown(result: dict) -> str:
    """Format structured result into Markdown with separate sections for
    confirmed and unverified eligibility."""
    if result.get("parse_failed"):
        return result.get("raw_text", "Erro ao gerar relatório.")

    today_dt = datetime.now(BRT)
    today = today_dt.strftime("%d/%m/%Y")
    year = today_dt.strftime("%Y")

    confirmed = result.get("opportunities_confirmed", [])
    unverified = result.get("opportunities_unverified", [])
    all_opps = confirmed + unverified

    urgent_count = sum(1 for o in all_opps if o.get("urgency") == "🔴")

    # Header
    header = HEADER_TEMPLATE.format(
        today=today,
        year=year,
        total_count=len(all_opps),
        confirmed_count=len(confirmed),
        unverified_count=len(unverified),
        urgent_count=urgent_count,
    )

    lines = [header, "---\n"]

    # --- Section 1: Confirmed eligibility ---
    if confirmed:
        lines.append("## ✅ OPORTUNIDADES COM ELEGIBILIDADE CONFIRMADA\n")
        lines.append("*Elegibilidade para organizações/profissionais brasileiros verificada na fonte oficial.*\n")

        for i, opp in enumerate(confirmed, 1):
            lines.extend(_format_opportunity(i, opp))

    # --- Section 2: Unverified eligibility ---
    if unverified:
        lines.append("---\n")
        lines.append("## ⚠️ OPORTUNIDADES COM ELEGIBILIDADE A VERIFICAR\n")
        lines.append("*A elegibilidade para o Brasil não pôde ser confirmada automaticamente. "
                      "Verifique nos links oficiais antes de investir tempo na aplicação.*\n")

        for i, opp in enumerate(unverified, len(confirmed) + 1):
            lines.extend(_format_opportunity(i, opp))

    # --- Strategic Recommendations ---
    recs = result.get("strategic_recommendations", [])
    if recs:
        lines.append("---\n")
        lines.append("## 3 PASSOS ESTRATÉGICOS PARA A ABRAJI\n")

        for i, rec in enumerate(recs, 1):
            title = rec.get("title", f"Recomendação {i}")
            action = rec.get("action", "")
            strategy = rec.get("strategy", "")
            relevant = rec.get("relevant_opportunities", [])
            deadline = rec.get("deadline_action", "")

            lines.append(f"### {i}. {title}\n")
            lines.append(f"**Ação:** {action}\n")
            lines.append(f"**Estratégia:** {strategy}\n")
            if relevant:
                lines.append(f"**Editais relacionados:** {', '.join(relevant)}\n")
            if deadline:
                lines.append(f"**Começar preparação até:** {deadline}\n")
            lines.append("")

    # Footer
    lines.append(FOOTER_TEMPLATE.format(model=GEMINI_MODEL))

    return "\n".join(lines)


def _format_opportunity(num: int, opp: dict) -> list[str]:
    """Format a single opportunity as Markdown lines."""
    urgency = opp.get("urgency", "🟢")
    elig_icon = classify_eligibility_display(opp)
    confidence = opp.get("eligibility_confidence", "unverified")

    lines = []
    lines.append(f"### {urgency} {num}. {opp['name']}\n")
    lines.append(f"**Financiador:** {opp['funder']}\n")
    lines.append(f"**Resumo Executivo:** {opp['summary']}\n")
    lines.append(f"**Valor do Financiamento:** {opp['amount_display']}\n")
    lines.append(f"**Deadline (Prazo):** {opp['deadline_display']}\n")
    lines.append(f"**Elegibilidade:** {elig_icon} {opp['eligibility']}\n")

    # Show eligibility details
    regions = opp.get("eligible_regions", [])
    if regions:
        lines.append(f"**Regiões elegíveis:** {', '.join(regions)}\n")

    if confidence == "partial":
        lines.append(f"**⚠️ Nota:** Brasil elegível como PARCEIRO, não como aplicante principal.\n")

    lines.append(f"**Tipo:** {opp.get('type', 'grant').capitalize()}\n")

    themes = opp.get("themes", [])
    if themes:
        lines.append(f"**Temas:** {', '.join(themes)}\n")

    lines.append(f"**Link Direto:** {opp['url']}\n")

    source = opp.get("eligibility_source", "")
    if source and source != opp.get("url", ""):
        lines.append(f"**Fonte de elegibilidade:** {source}\n")

    lines.append("")
    return lines


# ---------------------------------------------------------------------------
# HTML Email Building
# ---------------------------------------------------------------------------

def markdown_to_html(md_text: str) -> str:
    """Lightweight Markdown-to-HTML conversion for email rendering."""
    html = md_text

    html = html.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")

    html = re.sub(
        r"^### (.+)$",
        r"<h3 style='color:#1a5276;margin-top:24px;margin-bottom:8px;'>\1</h3>",
        html, flags=re.MULTILINE,
    )
    html = re.sub(
        r"^## (.+)$",
        r"<h2 style='color:#1a5276;margin-top:32px;border-bottom:2px solid #e8e8e8;padding-bottom:8px;'>\1</h2>",
        html, flags=re.MULTILINE,
    )
    html = re.sub(
        r"^# (.+)$",
        r"<h1 style='color:#1a5276;'>\1</h1>",
        html, flags=re.MULTILINE,
    )

    html = re.sub(r"\*\*(.+?)\*\*", r"<strong>\1</strong>", html)
    html = re.sub(r"\*(.+?)\*", r"<em>\1</em>", html)

    html = re.sub(
        r"\[([^\]]+)\]\((https?://[^\)]+)\)",
        r'<a href="\2" style="color:#2980b9;" target="_blank">\1</a>',
        html,
    )

    html = re.sub(
        r'(?<!href=")(https?://[^\s&lt;\)]+)',
        r'<a href="\1" style="color:#2980b9;" target="_blank">\1</a>',
        html,
    )

    html = re.sub(
        r"^- (.+)$",
        r"<li style='margin-bottom:4px;'>\1</li>",
        html, flags=re.MULTILINE,
    )

    html = re.sub(
        r"((?:<li[^>]*>.*?</li>\n?)+)",
        r"<ul style='margin:8px 0;padding-left:20px;'>\1</ul>",
        html,
    )

    html = re.sub(
        r"^---+$",
        r"<hr style='border:none;border-top:2px solid #e8e8e8;margin:24px 0;'>",
        html, flags=re.MULTILINE,
    )

    html = re.sub(r"\n\n", r"</p><p style='line-height:1.6;margin:8px 0;'>", html)
    html = html.replace("\n", "<br>\n")
    html = f"<p style='line-height:1.6;margin:8px 0;'>{html}</p>"

    return html


def build_email_html(report_md: str, result: dict) -> str:
    """Build a complete HTML email with eligibility sections."""
    today = datetime.now(BRT).strftime("%d/%m/%Y")

    confirmed = result.get("opportunities_confirmed", [])
    unverified = result.get("opportunities_unverified", [])
    all_opps = confirmed + unverified
    urgent_count = sum(1 for o in all_opps if o.get("urgency") == "🔴")

    report_html = markdown_to_html(report_md)

    # Urgent alerts
    summary_items = []
    for opp in all_opps:
        if opp.get("urgency") == "🔴" and opp.get("eligibility_confidence") in ("confirmed", "likely"):
            summary_items.append(
                f"<li>🔴 <strong>{opp['name']}</strong> — {opp.get('deadline_display', 'Verificar')}</li>"
            )

    urgent_section = ""
    if summary_items:
        urgent_section = f"""
        <div style="background:#fff3cd;border-left:4px solid #ffc107;padding:12px 16px;margin-bottom:20px;border-radius:4px;">
            <strong>⚡ Prazos urgentes (próximos 30 dias) — elegibilidade confirmada:</strong>
            <ul style="margin:8px 0;padding-left:20px;">
                {"".join(summary_items)}
            </ul>
        </div>
        """

    # Eligibility stats banner
    stats = result.get("stats", {})
    removed = stats.get("removed_count", 0)

    eligibility_note = ""
    if removed > 0 or len(unverified) > 0:
        eligibility_note = f"""
        <div style="background:#e8f4f8;border-left:4px solid #17a2b8;padding:12px 16px;margin-bottom:20px;border-radius:4px;">
            <strong>🔍 Verificação de elegibilidade (novidade v3):</strong><br>
            ✅ {len(confirmed)} oportunidades com elegibilidade confirmada para o Brasil<br>
            ⚠️ {len(unverified)} oportunidades com elegibilidade a verificar manualmente<br>
            {"❌ " + str(removed) + " oportunidades removidas (Brasil não elegível)<br>" if removed > 0 else ""}
            <em style="font-size:12px;">O sistema agora audita a elegibilidade geográfica de cada oportunidade
            para evitar falsos positivos.</em>
        </div>
        """

    return f"""<!DOCTYPE html>
<html lang="pt-BR">
<head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0"></head>
<body style="font-family:'Segoe UI',Arial,sans-serif;max-width:900px;margin:0 auto;
             padding:20px;color:#333;background-color:#f5f5f5;">

  <div style="background:linear-gradient(135deg, #1a5276, #2980b9);color:white;padding:28px 32px;border-radius:8px 8px 0 0;">
    <h1 style="margin:0;font-size:24px;">📡 Radar de Oportunidades — Abraji</h1>
    <p style="margin:8px 0 0;opacity:0.9;font-size:14px;">
      Relatório Automatizado de Grants &amp; Fellowships para Jornalismo · {today}
    </p>
    <p style="margin:4px 0 0;opacity:0.8;font-size:13px;">
      {len(all_opps)} oportunidades · {len(confirmed)} confirmadas · {urgent_count} urgentes
    </p>
  </div>

  <div style="background:white;padding:28px 32px;border-radius:0 0 8px 8px;
              box-shadow:0 2px 12px rgba(0,0,0,0.08);">

    {eligibility_note}
    {urgent_section}
    {report_html}
  </div>

  <div style="text-align:center;padding:16px;font-size:12px;color:#888;margin-top:12px;">
    Gerado automaticamente via GitHub Actions · Powered by Google {GEMINI_MODEL}<br>
    Abraji — Associação Brasileira de Jornalismo Investigativo<br>
    <em>Este relatório usa IA e busca web automatizada.
    Sempre verifique os links e prazos nos sites oficiais.</em><br><br>
    Script criado por Reinaldo Chaves
    (<a href="https://github.com/reichaves/grant-scanner" style="color:#2980b9;">github.com/reichaves</a>)
  </div>

</body>
</html>"""


# ---------------------------------------------------------------------------
# Email Sending
# ---------------------------------------------------------------------------

def send_email(
    sender: str,
    recipients: list[str],
    subject: str,
    html_body: str,
    plain_text: str,
    app_password: str,
) -> None:
    """Send HTML email via Gmail SMTP with App Password."""
    msg = MIMEMultipart("alternative")
    msg["From"] = f"Abraji Grant Scanner <{sender}>"
    msg["To"] = ", ".join(recipients)
    msg["Subject"] = subject
    msg["Reply-To"] = sender

    msg.attach(MIMEText(plain_text, "plain", "utf-8"))
    msg.attach(MIMEText(html_body, "html", "utf-8"))

    logger.info(f"Sending email to {len(recipients)} recipients via Gmail SMTP...")

    try:
        with smtplib.SMTP_SSL("smtp.gmail.com", 465) as server:
            server.login(sender, app_password)
            server.sendmail(sender, recipients, msg.as_string())
        logger.info("Email sent successfully!")
    except smtplib.SMTPAuthenticationError:
        logger.error(
            "Gmail authentication failed. Check your App Password. "
            "Ensure 2FA is enabled and you're using an App Password."
        )
        sys.exit(1)
    except Exception as e:
        logger.error(f"Email sending failed: {e}")
        sys.exit(1)


# ---------------------------------------------------------------------------
# Persistence
# ---------------------------------------------------------------------------

def save_report_data(result: dict, path: str = PREVIOUS_REPORT_PATH) -> None:
    """Save structured report data for comparison in next run."""
    try:
        with open(path, "w", encoding="utf-8") as f:
            json.dump(result, f, ensure_ascii=False, indent=2)
        logger.info(f"Report data saved to {path}")
    except Exception as e:
        logger.warning(f"Could not save report data: {e}")


def load_previous_report(path: str = PREVIOUS_REPORT_PATH) -> Optional[dict]:
    """Load previous report data if available."""
    try:
        if Path(path).exists():
            with open(path, "r", encoding="utf-8") as f:
                return json.load(f)
    except Exception as e:
        logger.warning(f"Could not load previous report: {e}")
    return None


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main():
    logger.info("=" * 60)
    logger.info("GRANT SCANNER v3 — Starting execution")
    logger.info("=" * 60)

    gemini_api_key = get_env_var("GEMINI_API_KEY")
    gmail_app_password = get_env_var("GMAIL_APP_PASSWORD")

    # Step 1: Run the AI-powered web search (three passes)
    result = run_grant_search(gemini_api_key)

    # Step 2: Format the report
    report_md = format_report_markdown(result)

    # Step 3: Build and send the email
    today = datetime.now(BRT).strftime("%d/%m/%Y")
    confirmed = result.get("opportunities_confirmed", [])
    unverified = result.get("opportunities_unverified", [])
    all_opps = confirmed + unverified
    urgent_count = sum(1 for o in all_opps if o.get("urgency") == "🔴")

    subject = f"📡 Radar de Grants — Abraji — {today} ({len(confirmed)} confirmadas"
    if len(unverified) > 0:
        subject += f", {len(unverified)} a verificar"
    if urgent_count > 0:
        subject += f", {urgent_count} urgentes"
    subject += ")"

    html_body = build_email_html(report_md, result)
    plain_text = f"Radar de Oportunidades — Abraji — {today}\n\n{report_md}"

    send_email(SENDER_EMAIL, RECIPIENTS, subject, html_body, plain_text, gmail_app_password)

    # Step 4: Save artifacts
    report_path = "grant_report.md"
    with open(report_path, "w", encoding="utf-8") as f:
        f.write(f"# Radar de Oportunidades — Abraji — {today}\n\n")
        f.write(report_md)
    logger.info(f"Markdown report saved to {report_path}")

    save_report_data(result)

    json_path = "grant_report.json"
    with open(json_path, "w", encoding="utf-8") as f:
        json.dump(result, f, ensure_ascii=False, indent=2)
    logger.info(f"JSON report saved to {json_path}")

    logger.info("=" * 60)
    logger.info(
        f"GRANT SCANNER v3 — Done: {len(confirmed)} confirmed, "
        f"{len(unverified)} unverified, {urgent_count} urgent"
    )
    logger.info("=" * 60)


if __name__ == "__main__":
    main()
