"""
Configuration constants for the grant scanner.

All environment-independent settings live here.
Runtime secrets (API keys, passwords) are read from env vars in grant_scanner.py.
"""

from datetime import timezone, timedelta

# ---------------------------------------------------------------------------
# Timezone
# ---------------------------------------------------------------------------
BRT = timezone(timedelta(hours=-3))

# ---------------------------------------------------------------------------
# Gemini model
# ---------------------------------------------------------------------------
#GEMINI_MODEL = "gemini-3-pro-preview"
GEMINI_MODEL = "gemini-3.1-pro-preview"

# ---------------------------------------------------------------------------
# Email
# ---------------------------------------------------------------------------
SENDER_EMAIL = "reichaves@gmail.com"


RECIPIENTS = [
    "reinaldo@abraji.org.br",
    "anacarolinamoreno@abraji.org.br",
    "sergioludtke@abraji.org.br",
    "leticiakleim@abraji.org.br",
]


"""
RECIPIENTS = [
    "reinaldo@abraji.org.br"
]
"""

# ---------------------------------------------------------------------------
# Persistence
# ---------------------------------------------------------------------------
PREVIOUS_REPORT_PATH = "previous_grant_report.json"

# ---------------------------------------------------------------------------
# Report templates (static, NOT generated by the LLM)
# ---------------------------------------------------------------------------
HEADER_TEMPLATE = """RELATÓRIO DE OPORTUNIDADES DE FINANCIAMENTO: JORNALISMO E MÍDIA
Data do Relatório: {today}
Preparado para: Abraji (Associação Brasileira de Jornalismo Investigativo)
Período de cobertura: Oportunidades com prazo aberto ou previsto para {year}
Total de oportunidades identificadas: {total_count}
├─ ✅ Elegibilidade confirmada: {confirmed_count}
├─ ⚠️ Elegibilidade a verificar: {unverified_count}
└─ 🔴 Prazo urgente (< 30 dias): {urgent_count}

LEGENDA DE URGÊNCIA:
🔴 URGENTE — Prazo em menos de 30 dias
🟡 ATENÇÃO — Prazo entre 30 e 90 dias
🟢 PLANEJAMENTO — Prazo acima de 90 dias ou fluxo contínuo

LEGENDA DE ELEGIBILIDADE:
✅ CONFIRMADA — Página oficial menciona Brasil/LatAm/Global explicitamente
⚠️ NÃO VERIFICADA — Elegibilidade para o Brasil não pôde ser confirmada na fonte
🔗 PARCIAL — Brasil elegível como parceiro, não como aplicante principal
"""

FOOTER_TEMPLATE = """
---
Gerado automaticamente via GitHub Actions · Powered by Google {model}
Abraji — Associação Brasileira de Jornalismo Investigativo
⚠️ Este relatório usa IA e busca web automatizada. Sempre verifique os links e prazos nos sites oficiais.
Script criado por Reinaldo Chaves (https://github.com/reichaves)
"""

__all__ = [
    "BRT",
    "GEMINI_MODEL",
    "SENDER_EMAIL",
    "RECIPIENTS",
    "PREVIOUS_REPORT_PATH",
    "HEADER_TEMPLATE",
    "FOOTER_TEMPLATE",
]
